```{r fig-2-supplement-setup}
knitr::opts_chunk$set(
  fig.path = "./fig-2-supplement/"
)

cbPalette <- c("#DC5E65", "#E69F00", "#56B4E9",
  "#0072B2", "darkgrey", "#009E73", 
  "#F0E442", "pink", "#CC79A7",
  "lightgrey", "grey")

aa_order <- c("*", "P", "G", "A", "M",
  "V", "L", "I", "T", "S",
  "C", "Q", "N", "Y", "W",
  "F", "E", "D", "K", "H", "R")

ifna_series <- bind_rows(
  contrast_sumstats %>% filter(condition == "IFNalpha100_0", assay == "assay3") %>% mutate(condition = "IFNa 100 U/mL"),
  contrast_sumstats %>% filter(condition == "IFNalpha_10", assay == "assay1") %>% mutate(condition = "IFNa 10 U/mL"),
  contrast_sumstats %>% filter(condition == "IFNalpha_1", assay == "assay1") %>% mutate(condition = "IFNa 1 U/mL")
) %>% select(pos, condition, aa, statistic_contrast) %>%
  rename("statistic" = "statistic_contrast")

flow_series <- flow_data %>% 
  select(pos, aa, statistic) %>%
  mutate(condition = "Abundance")

fig_data <- bind_rows(ifna_series, flow_series) %>%
  mutate(aa = if_else(aa %in% c("*", "Stop", "X"), "*", aa),
    aa = factor(aa, levels = aa_order),
    condition = factor(condition, levels = c("IFNa 1 U/mL",
      "IFNa 10 U/mL",
      "IFNa 100 U/mL",
      "Abundance")))
```

```{r supp-fig-2, fig.width = 8, fig.height = 15}
supp_fig_2 <- fig_data %>% 
  ggplot() +
    geom_tile(aes(x = pos, y = aa, fill = statistic)) +
    scale_fill_scico_mid("Z statistic", limits = c(-10, 2.5),
      palette = "vik", mid = 0,
      oob = scales::squish) +
    scale_x_continuous(breaks = seq(0, 1000, by = 250),
      expand = c(0, 0)) +
    ylab("") +
    xlab("TYK2 Amino Acid Position") +
    custom_theme +
    facet_wrap(~condition, ncol = 1) +
    theme(legend.position = "top")

supp_fig_2
```
