```{r fig-1-setup}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.path = "./fig-1/",
  warning = FALSE,
  message = FALSE,
  dev = c("png", "pdf")
)

aa_order <- c("Stop", "P", "G", "A", "M", "V", "L", "I", "T", "S",
              "C", "Q", "N", "Y", "W", "F", "E", "D", "K", "H", "R")

ifna_signaling <- read_tsv("../sumstats/TYK2-run3.sumstats.tsv", show_col_types = FALSE) %>%
    filter(condition == "IFNalpha100_0") %>%
    mutate(aa = if_else(aa %in% c("X", "Stop", "*"), "Stop", aa),
           aa = factor(aa, levels = aa_order))
stability <- read_tsv("../sumstats/TYK2-vamp2.midpoints.tsv", show_col_types = FALSE) %>%
    mutate(aa = if_else(aa %in% c("X", "Stop", "*"), "Stop", aa),
           aa = factor(aa, levels = aa_order))
```

### Main Heatmaps

```{r main-heatmap-activity, fig.width=8, fig.height=12}
norm_heat_l2fc <- ifna_signaling %>%
    ggplot() +
        geom_tile(aes(y = pos, x = aa, fill = log2FoldChange)) +
        scale_fill_scico_mid(limits = c(-3,1), palette = "vik", mid = 0, oob = squish) +
        xlab("") + ylab("TYK2 Amino Acid Position") +
        ggtitle("TYK2 // Assay 3 // IFN-alpha 100 U/mL") +
        scale_y_reverse() +
        theme_bw(base_size = 8)

norm_heat_z <- ifna_signaling %>%
    rename("Z-Statistic" = "statistic") %>%
    ggplot() +
        geom_tile(aes(y = pos, x = aa, fill = `Z-Statistic`)) +
        scale_fill_scico_mid( limits = c(-10,2.5), palette = "vik", mid = 0, oob = squish) +
        xlab("") + ylab("TYK2 Amino Acid Position") +
        ggtitle("TYK2 // Assay 3 // IFN-alpha 100 U/mL") +
        scale_y_reverse() +
        theme_bw(base_size = 8)

norm_heat_l2fc + norm_heat_z
```

```{r main-heatmap-stability, fig.width=8, fig.height=12}
norm_heat_l2fc <- stability %>%
    rename("Midpoint Shift" = "midpoint_shift") %>%
    ggplot() +
        geom_tile(aes(y = pos, x = aa, fill = `Midpoint Shift`)) +
        scale_fill_scico_mid(limits = c(-0.75, 0.25), palette = "vik", mid = 0, oob = squish) +
        xlab("") + ylab("TYK2 Amino Acid Position") +
        ggtitle("TYK2 // FlowDMS") +
        theme_bw(base_size = 8) +
        scale_y_reverse()

norm_heat_z <- stability %>%
    rename("Z-Statistic" = "statistic") %>%
    ggplot() +
        geom_tile(aes(y = pos, x = aa, fill = `Z-Statistic`)) +
        scale_fill_scico_mid( limits = c(-10,2.5), palette = "vik", mid = 0, oob = squish) +
        xlab("") + ylab("TYK2 Amino Acid Position") +
        ggtitle("TYK2 // FlowDMS") +
        theme_bw(base_size = 8) +
        scale_y_reverse()

norm_heat_l2fc + norm_heat_z
```


