---
title: "TYK2 Analysis - Supplementary Figure 3"
author: "Nathan Abell and Robert Warneford-Thomson"
format: gfm
code-fold: true
knitr:
  opts_chunk:
    fig.align: "center"
---

```{r}
#| label: fig-3-supplement-setup
#| echo: false
#| warning: false
#| message: false

cbPalette <- c("#DC5E65", "#E69F00", "#56B4E9",
  "#0072B2", "darkgrey", "#009E73", 
  "#F0E442", "pink", "#CC79A7",
  "lightgrey", "grey")

aa_order <- c("*", "P", "G", "A", "M",
  "V", "L", "I", "T", "S",
  "C", "Q", "N", "Y", "W",
  "F", "E", "D", "K", "H", "R")

ifna_series <- bind_rows(
  assay3 %>% filter(condition == "IFNalpha100_0") %>% mutate(condition = "IFNa 100 U/mL"),
  assay1 %>% filter(condition == "IFNalpha_10") %>% mutate(condition = "IFNa 10 U/mL"),
  assay1 %>% filter(condition == "IFNalpha_1") %>% mutate(condition = "IFNa 1 U/mL")
) %>% select(pos, condition, aa, statistic)

flow_series <- stability %>% 
  select(pos, aa, statistic) %>%
  mutate(condition = "Abundance")

fig_data <- bind_rows(ifna_series, flow_series) %>%
  mutate(aa = if_else(aa %in% c("*", "Stop", "X"), "*", aa),
    condition = factor(condition, levels = c("IFNa 1 U/mL",
      "IFNa 10 U/mL",
      "IFNa 100 U/mL",
      "Abundance")))

tyk2_clinvar <- read_tsv("data/clinvar_TYK2_20250109.tsv", show_col_types = FALSE)  %>%
  filter(type == "missense variant") %>%
  mutate(class = if_else(class %in% c("Benign",
    "Benign/Likely benign",
    "Likely benign"),
    "Benign", class))
```

### Panel A

```{r S1x2-A, fig.width=5, fig.height=5}
A <- fig_data %>%
  mutate(status = case_when(statistic < 0 & p.adj < 0.01 ~ "LoF",
    statistic > 0 & p.adj < 0.01 ~ "GoF",
    .default = "no effect"
  )) %>%
  mutate(status = factor(status, levels = c("GoF", "no effect", "LoF"))) %>%
  ggplot(aes(x = condition, fill = status)) +
  geom_bar(position = "fill") +
  geom_label(aes(label = after_stat(count)),
    stat = "count",
    position = position_fill(vjust = 0.5),
    show.legend = FALSE,
    size = rel(2),
  ) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual("", values = c("#DC5E65", "lightgrey", "#0072B2")) +
  custom_theme
```

### Fig S1x2-B - stop effect density plots

```{r S1x2-B, fig.width=8, fig.height=8}
B <- merge_sumstats %>%
  # dplyr::filter(grepl("- None0", condition)) %>%
  mutate(group = factor(if_else(aa == "*", "stop variants", "other variants"),
                        levels = c("stop variants", "other variants"))) %>%
  ggplot() +
  geom_density(
    aes(
      x = z_statistic, group = group,
      fill = group
    ),
    color = NA,
    alpha = 0.5
  ) +
  geom_text(aes(label = facet_label), x = -15, y = 0.4, size = rel(2), hjust = 0) +
  facet_grid2(facet_label ~ ., scales = "fixed") +
  scale_fill_manual("", values = c(
    "stop variants" = "red",
    "other variants" = "black")) +
  labs(
    x = "Z-Statistic",
    y = "Density",
    # title = "Fig S1D",
    # subtitle = "IFN\u03B1 data normalized 0 cytokine condition"
  ) +
  coord_cartesian(xlim = c(-15, 7)) +
  scale_y_continuous(breaks = 0.5) +
  # scale_x_continuous(expand = c(0, 0)) +
  theme_pub(base_size = 12) +
  theme(
    axis.title = element_text(size = rel(0.6)),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.box = element_blank(),
    legend.position = "top",
    legend.key = element_rect(color = NA),
    legend.margin = margin(0,0,-25,0),
    legend.box.spacing = unit(0.001, "npc"),
    legend.title = element_blank(),
    legend.text = element_text(size = rel(0.5)),
    legend.key.height = unit(0.01, "npc"),
    strip.text.y = element_blank(),# element_text(angle = 0, size = rel(0.7)),
    axis.text= element_text(size = unit(6, "points")),
    plot.tag.position = c(0.01, 0.9)
  )
```

### Fig S1x2-C - AlphaMissense

```{r S1x2-C, fig.width=8, fig.height=8}
am_df <-  anno_df %>% 
  dplyr::filter(classifier == "AlphaMissense")

C <- am_df %>%
    ggplot(aes(x = classifier_value, y = z_statistic,
             color = classifier_value)) +
  geom_quasirandom_rast(size = 0.5,
                        show.legend = FALSE) +
  # geom_violin(
  #   aes(fill = classifier_value),
  #   scale = "width",
  #   show.legend = FALSE
  #   ) +
  geom_boxplot(show.legend = FALSE,
               col = "black",
               outliers = FALSE,
               width = 0.09) +
  scale_color_manual(values = c(
    "Pathogenic" = "#DC5E65",
      "Ambiguous" =  "#E69F00",
      "Benign" =  "#0072B2")
  ) +
    scale_fill_manual(values = c(
    "Pathogenic" = "#DC5E65",
      "Ambiguous" =  "#E69F00",
      "Benign" =  "#0072B2")
  ) +
  # add significance calculation using KS test
  geom_signif(
    color = "black",
    comparisons = list(
      c("Pathogenic", "Ambiguous"),
      c("Pathogenic", "Benign"),
      c("Ambiguous", "Benign")
    ),
    map_signif_level = function(p) {
      if(p < 0.001) return("***")
      else if(p < 0.01) return("**")
      else if(p < 0.05) return("*")
      else return("ns")
    },
    test = "ks.test",
    margin_top = 0.01,
    step_increase = 0.025,
    tip_length = 0.005,
    vjust = 0.65,
    size = 0.5,
    textsize = 3
  ) +
  facet_grid2(. ~ facet_label,
              scales = "free_y",
              space = "free") +
  labs(
    x = "AlphaMissense annotation",
    y = "Z statistic",
  ) +
  ylim(-15,7) +
  theme_pub(base_size = 11) +
  theme(
    plot.title = element_blank(),
    axis.text.x = element_text(size = rel(0.8)),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = rel(0.6)),
    strip.text.x = element_text(size = rel(0.7)),
    plot.tag.position = c(0.01, 0.98)
    )

```

### Fig S1x2-D - Fiducial variant forest plot

```{r S1x2-D, fig.width=12, fig.height=6}
spikeins <- read_tsv("../paper/data/tyk2-spikeins.tsv",
  col_names = c("pos", "mut_id", "class")
) %>%
  mutate(
    class = if_else(class == "-", "Unknown", class),
    class = factor(class, levels = c("LOF", "Unknown", "GOF"))
  ) %>%
  arrange(class, pos) %>%
  separate_wider_regex(mut_id,
    patterns = c(".*\\d+", "aa" = ".*"),
    cols_remove = FALSE
  ) %>%
  mutate(aa = ifelse(aa == "Stop", "*", aa)) 


spikeins$mut_id <- factor(spikeins$mut_id, levels = spikeins$mut_id)

spikeins_join <- spikeins %>%
  inner_join(merge_sumstats, by = c("pos", "aa")) %>%
  arrange(class, pos) %>%
  mutate(class = factor(class, levels = c("GOF", "Unknown", "LOF"))) %>%
  mutate(facet_label = str_replace_all(facet_label, "([0-1]+)", "\n\\1")) %>%
  mutate(facet_label = fct_relevel(facet_label, "Abundance", after = Inf)) %>% 
  mutate(significance = factor(if_else(p.adj < 0.01, "FDR < 1%", "not significant")))

D1 <- spikeins_join %>% 
  filter(facet_label != "Abundance") %>% 
  ggplot() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 26.5,
             color = "#DC5E65",
             linetype = "dashed") +
  geom_text(
    data = tibble(facet_label = "IFNα \n1 U/mL",
                  label = "GOF"),
    aes(label = label),
    color = "#DC5E65",
    y = 28.5,
    x = -1.5
  ) +
  geom_hline(yintercept = 15.5,
             color = "#0072B2",
             linetype = "dashed") +
    geom_text(
    data = tibble(facet_label = "IFNα \n1 U/mL",
                  label = "LOF"),
    aes(label = label),
    color = "#0072B2",
    y = 12.5,
    x = -1.5
  ) +
  geom_pointrange(
    aes(
      x = param_estimate,
      y = factor(mut_id),
      xmin = param_estimate - 2 * param_se,
      xmax = param_estimate + 2 * param_se,
      color = significance
    ),
    linewidth = 0.25,
    size = 0.1
  ) +
  theme_pubr(base_size = 13) +
  labs(
    x = expression(Log[2]~fold~change~"\u00B1"~2~standard~errors),
    y = "") +
    #," ± 2 standard errors"),
  #  subtitle = "IFNa data normalized to 0 cytokine control\nEffect size = log2FoldChange for IFNa data\nEffect size = midpoint shift for Abundance DMS (see methods)\nPoints in black (padj < 0.01)"
  scale_color_manual("", values = c("black", "lightgrey")) +
  xlim(c(-2.5, 1)) +
  theme_pub(base_size = 11) +
  theme(
    panel.grid.major.x = element_blank(),
    strip.text.x = element_text(size = unit(6, "points")),
    axis.title = element_text(size = rel(0.6)),
    legend.position = "top",
    legend.margin=margin(0,0,-10,0),
    axis.text.y = element_text(size = unit(6, "points")),
    axis.text.x = element_text(angle = 0, hjust = 0.6,
                               size = unit(6, "points")),
    panel.grid.major.y = element_blank(),
    plot.tag.position = c(0.01, 0.98)
  ) +
  facet_grid2(. ~ facet_label, scales = "fixed")

#panel for abundance DMS
D2 <- spikeins_join %>% 
  filter(facet_label == "Abundance") %>% 
  ggplot() +
  geom_vline(xintercept = 0) +
   geom_hline(yintercept = 26.5,
             color = "#DC5E65",
             linetype = "dashed") +
  geom_hline(yintercept = 15.5,
             color = "#0072B2",
             linetype = "dashed") +
  geom_pointrange(
    aes(
      x = param_estimate,
      y = mut_id,
      xmin = param_estimate - 2 * param_se,
      xmax = param_estimate + 2 * param_se,
      color = significance
    ),
    linewidth = 0.25,
    size = 0.1,
    show.legend = FALSE
  ) +
  theme_pubr(base_size = 13) +
  labs(
    x = "Midpoint shift\n± 2 standard errors",
    y = "",
    # title = "Fig S1E",
  #  subtitle = "IFNa data normalized to 0 cytokine control\nEffect size = log2FoldChange for IFNa data\nEffect size = midpoint shift for Abundance DMS (see methods)\nPoints in black (padj < 0.01)"
  ) +
  scale_color_manual("", values = c("black", "lightgrey")) +
  scale_x_continuous(limits = c(-1,1),
                     breaks = c(-1,0,1)) +
  theme_pub(base_size = 11) +
  theme(
    panel.grid.major.x = element_blank(),
    strip.text.x = element_text(size = unit(6, "points")),
    axis.title = element_text(size = rel(0.6)),
    axis.text.y = element_blank(),
    plot.margin = margin(0,0,0,10),
    axis.ticks.y = element_blank(),
    # axis.text.y = element_text(size = unit(4, "points")),
    axis.text.x = element_text(angle = 0, hjust = 0.6,
                               size = unit(6, "points")),
    panel.grid.major.y = element_blank(),
    plot.tag.position = c(0.01, 0.98)
  ) +
  facet_grid2(. ~ facet_label)

D <- D1 + (D2 + plot_layout(tag_level = "new")) +
  plot_layout(widths = c(3,1))
```

### Fig S1x2-E - ClinVar annotation

```{r S1x2-E, fig.width=8, fig.height=8}
anno_df <- anno_df %>% 
  mutate(classifier_value = fct_recode(classifier_value, "Conflicting\nClassifications\nOf Pathogenicity" = "Conflicting Classifications Of Pathogenicity",
                                       "Uncertain\nSignificance"  = "Uncertain Significance",
                                       "Benign/\nLikely Benign" = "Benign/Likely Benign"))

counts <- anno_df %>% 
  dplyr::filter(classifier == "clinvar") %>% 
  select(mut, classifier_value) %>% 
  distinct() %>% 
  group_by(classifier_value) %>% 
  summarise(count = n())

E <- anno_df %>% 
  dplyr::filter(classifier == "clinvar") %>% 
  left_join(counts) %>% 
  arrange(classifier_value) %>%
  # mutate(classifier_value_count = paste("count", count)) %>% 
  mutate(classifier_value_count =  fct_inorder(paste0(classifier_value, " (", format(count, big.mark = ",", trim = TRUE),")"))) %>%
  ggplot(aes(
    x = z_statistic,
    y = classifier_value_count,
    color = classifier_value_count,
             fill = classifier_value_count)) +
  geom_vline(xintercept = 0, color = "lightgrey", width = 0.5) +
  geom_quasirandom_rast(orientation = "y",
                   size = 0.5,
                   width = 0.2,
                   varwidth = TRUE,
                   show.legend = FALSE) +
  scale_color_manual(values = cbPalette) +
  scale_fill_manual(values = cbPalette) +
  facet_grid2(. ~ facet_label,
              scales = "free_x",
              space = "free") +
  labs(
    x = "Z statistic",
    y = "Clinvar annotation",
  ) +
  theme_pub(base_size = 11) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.6),
        axis.text.y = element_text(angle = 0, hjust = 0.5),
        axis.text= element_text(size = unit(6, "points")),
        strip.text.y = element_text(angle = 0, size = unit(8, "points")),
        axis.title = element_text(size = unit(10, "points")),
        plot.tag.position = c(0.01, 0.98)
        )
```

## Merged Figure S1x2

```{r fig-S1x2-merged, fig.width=8.5, fig.height=11}
layout <- c(
  area(1, 1, 1, 1),
  area(1, 2, 1, 2),
  area(1, 3, 1, 3),
  area(2, 1, 2, 2),
  area(2, 3, 2, 3)
)
A + free(B, type = "label") + free(C, side = "l") + free(D) + E +
  plot_layout(heights = c(1, 1),
              guides = "keep",
              design = layout) +
  plot_annotation(tag_levels = "A") &
  theme(
    legend.key = element_blank(),
    panel.grid.major.y = element_blank(),
    axis.title = element_text(size = unit(8, "points")),
    axis.text = element_text(size = unit(6, "points")),
    plot.tag = element_text(size = unit(14, "points")),
    # plot.title = element_text(size = unit(14, "points")),
    legend.text = element_text(size = unit(8, "points")),
    # strip.text.x = element_blank(),
    strip.text.x = element_text(size = unit(6, "points")),
    plot.tag.position = c(0.01, 1.01)
  )

```
