```{r fig-3-supplement-setup}
knitr::opts_chunk$set(
  fig.path = "./fig-3-supplement/"
)

library(ggh4x)
library(ggsignif)
library(ggrastr)
library(ggpubr)

cbPalette <- c("#DC5E65", "#E69F00", "#56B4E9",
  "#0072B2", "darkgrey", "#009E73", 
  "#F0E442", "pink", "#CC79A7",
  "lightgrey", "grey")

aa_order <- c("*", "P", "G", "A", "M",
  "V", "L", "I", "T", "S",
  "C", "Q", "N", "Y", "W",
  "F", "E", "D", "K", "H", "R")

aa_table <- read_tsv("data/aa-letters.tsv", show_col_types = FALSE, col_names = c("aa_full", "aa_3", "aa")) %>%
  select(-aa_full)

ifna_series <- bind_rows(
  contrast_sumstats %>% filter(condition == "IFNalpha100_0", assay == "assay3") %>% mutate(condition = "IFNa 100 U/mL"),
  contrast_sumstats %>% filter(condition == "IFNalpha_10", assay == "assay1") %>% mutate(condition = "IFNa 10 U/mL"),
  contrast_sumstats %>% filter(condition == "IFNalpha_1", assay == "assay1") %>% mutate(condition = "IFNa 1 U/mL")
) %>% select(pos, condition, aa, log2Contrast, log2ContrastError, statistic_contrast, fdr_contrast) %>%
  rename("effect" = "log2Contrast",
         "error" = "log2ContrastError",
      "statistic" = "statistic_contrast",
      "p.adj" = "fdr_contrast")

flow_series <- flow_data %>%
  mutate(condition = "Abundance") %>%
  select(pos, aa, condition, midpoint_shift, midpoint_shift_se, statistic, p.adj) %>%
    rename("effect" = "midpoint_shift",
           "error" = "midpoint_shift_se")

fig_data <- bind_rows(ifna_series, flow_series) %>%
  mutate(aa = if_else(aa %in% c("*", "Stop", "X"), "*", aa),
    aa = factor(aa, levels = aa_order),
    condition = factor(condition, levels = c("IFNa 1 U/mL",
      "IFNa 10 U/mL",
      "IFNa 100 U/mL",
      "Abundance")))

tyk2_clinvar <- read_tsv("data/clinvar_TYK2_20250109.tsv", show_col_types = FALSE) %>%
  filter(type == "missense variant") %>%
  mutate(class = if_else(class %in% c("Benign",
    "Benign/Likely benign",
    "Likely benign"),
    "Benign/Likely benign", class),
    aa_3 = str_sub(variant, -3, -1),
    pos = as.numeric(str_sub(variant, 4, -4))) %>%
  left_join(aa_table, by = "aa_3") %>%
  select(class, pos, aa) %>%
  distinct()

tyk2_clinvar_joined <- fig_data %>%
  left_join(tyk2_clinvar, by = c("pos", "aa"))

am_df <-  read_tsv("data/TYK2.Uniprot.P29597.AlphaMissense_aa.substitutions.tsv",
  show_col_types = FALSE,
  col_names = c("uniprot", "variant", "score", "classifier_value")) %>%
  mutate(aa = str_sub(variant, -1),
    pos = as.numeric(str_sub(variant, 2, -2)),
    classifier_value = factor(classifier_value, levels = c("Pathogenic", "Ambiguous", "Benign"))) %>%
  inner_join(fig_data, by = c("pos", "aa")) %>%
  filter(condition == "IFNa 100 U/mL" | condition == "Abundance")

spikeins <- read_tsv("data/tyk2-spikeins.tsv", show_col_types = FALSE,
                     col_names = c("pos", "mut_id", "class")) %>%
  mutate(class = if_else(class == "-", "Unknown", class),
    class = factor(class, levels = c("LOF", "Unknown", "GOF")),
    mut_id = gsub("Stop", "*", mut_id),
    aa = str_sub(mut_id, -1),
    pos = as.numeric(str_sub(mut_id, 2, -2))) %>%
  arrange(class, pos) %>%
  mutate(aa = ifelse(aa %in% c("*", "Stop", "X"), "*", aa)) 

spikeins$mut_id <- factor(spikeins$mut_id, levels = spikeins$mut_id)

spikeins_join <- spikeins %>%
  inner_join(fig_data, by = c("pos", "aa")) %>%
  arrange(class, pos) %>%
  mutate(class = factor(class, levels = c("GOF", "Unknown", "LOF")),
    significance = factor(if_else(p.adj < 0.01, "FDR < 1%", "not significant")))
```

### Panel A

```{r supp-fig-3-A, fig.width=5, fig.height=5}
A <- fig_data %>%
  mutate(status = case_when(statistic < 0 & p.adj < 0.01 ~ "LoF",
    statistic > 0 & p.adj < 0.01 ~ "GoF",
    .default = "no effect"
  )) %>%
  mutate(status = factor(status, levels = c("GoF", "no effect", "LoF"))) %>%
  ggplot(aes(x = condition, fill = status)) +
  geom_bar(position = "fill") +
  geom_label(aes(label = after_stat(count)),
    stat = "count",
    position = position_fill(vjust = 0.5),
    show.legend = FALSE,
    size = rel(2),
  ) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual("", values = c("#DC5E65", "lightgrey", "#0072B2")) +
  custom_theme +
  theme(
    axis.title = element_text(size = rel(0.6)),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.box = element_blank(),
    legend.position = "top",
    legend.key = element_rect(color = NA),
    legend.margin = margin(0,0,-25,0),
    legend.box.spacing = unit(0.001, "npc"),
    legend.title = element_blank(),
    legend.text = element_text(size = rel(0.5)),
    legend.key.height = unit(0.01, "npc"),
    strip.text.y = element_blank(),
    axis.text= element_text(size = unit(6, "points")),
    plot.tag.position = c(0.01, 0.9)
  )
```

### Panel B

```{r supp-fig-3-B, fig.width=8, fig.height=8}
B <- fig_data %>%
  mutate(group = factor(if_else(aa == "*", "stop variants", "other variants"),
                        levels = c("stop variants", "other variants"))) %>%
  ggplot() +
  geom_density(
    aes(
      x = statistic, group = group,
      fill = group
    ),
    color = NA,
    alpha = 0.5
  ) +
  geom_text(aes(label = condition), x = -15, y = 0.4, size = rel(2), hjust = 0) +
  facet_grid2(condition ~ ., scales = "fixed") +
  scale_fill_manual("", values = c(
    "stop variants" = "red",
    "other variants" = "black")) +
  labs(
    x = "Z-Statistic",
    y = "Density"
  ) +
  coord_cartesian(xlim = c(-15, 7)) +
  scale_y_continuous(breaks = 0.5) +
  custom_theme +
  theme(
    axis.title = element_text(size = rel(0.6)),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.box = element_blank(),
    legend.position = "top",
    legend.key = element_rect(color = NA),
    legend.margin = margin(0,0,-25,0),
    legend.box.spacing = unit(0.001, "npc"),
    legend.title = element_blank(),
    legend.text = element_text(size = rel(0.5)),
    legend.key.height = unit(0.01, "npc"),
    strip.text.y = element_blank(),
    axis.text= element_text(size = unit(6, "points")),
    plot.tag.position = c(0.01, 0.9)
  )
```

### Panel C
```{r supp-fig-3-C, fig.width=8, fig.height=8}
class_colors <- c("Pathogenic" = "#DC5E65", "Ambiguous" =  "#E69F00", "Benign" =  "#0072B2")

C <- am_df %>%
  ggplot(aes(x = classifier_value, y = statistic,
             color = classifier_value)) +
  geom_quasirandom_rast(size = 0.5,
                        show.legend = FALSE) +
  geom_boxplot(show.legend = FALSE,
               col = "black",
               outliers = FALSE,
               width = 0.09) +
  scale_color_manual(values = class_colors) +
  scale_fill_manual(values = class_colors) +
  # add significance calculation using KS test
  geom_signif(
    color = "black",
    comparisons = list(
      c("Pathogenic", "Ambiguous"),
      c("Pathogenic", "Benign"),
      c("Ambiguous", "Benign")
    ),
    map_signif_level = function(p) {
      if(p < 0.001) return("***")
      else if(p < 0.01) return("**")
      else if(p < 0.05) return("*")
      else return("ns")
    },
    test = "ks.test",
    margin_top = 0.01,
    step_increase = 0.025,
    tip_length = 0.005,
    vjust = 0.65,
    size = 0.5,
    textsize = 3
  ) +
  facet_grid2(. ~ condition, scales = "free_y", space = "free") +
  labs(x = "AlphaMissense annotation", y = "Z statistic") +
  ylim(-15,7) +
  custom_theme +
  theme(
    plot.title = element_blank(),
    axis.text.x = element_text(size = rel(0.8)),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = rel(0.6)),
    strip.text.x = element_text(size = rel(0.7)),
    plot.tag.position = c(0.01, 0.98)
  )
```

### Panel D

```{r supp-fig-3-D, fig.width=12, fig.height=6}
D1 <- spikeins_join %>% 
  filter(condition != "Abundance") %>% 
  mutate(condition = gsub("IFNa", "IFNa\n", condition)) %>%
  ggplot() +
  geom_vline(xintercept = 0) +
  annotate(xmin = -Inf, xmax = Inf, ymin = 26.5, ymax = Inf,
    fill = "#DC5E65",
    geom = "rect",
    alpha = 0.2) +
  annotate(xmin = -Inf, xmax = Inf, ymin = 15.5, ymax = -Inf,
    fill = "#0072B2",
    geom = "rect",
    alpha = 0.2) +
  geom_pointrange(
    aes(
      x = effect,
      y = factor(mut_id),
      xmin = effect - 2 * error,
      xmax = effect + 2 * error,
      color = significance
    ),
    linewidth = 0.25,
    size = 0.1
  ) +
  theme_pubr(base_size = 13) +
  labs(
    x = expression(Log[2]~fold~change~" +/- 2 standard errors"),
    y = "") +
  scale_color_manual("", values = c("black", "lightgrey")) +
  xlim(c(-2.5, 1)) +
  custom_theme +
  theme(
    panel.grid.major.x = element_blank(),
    strip.text.x = element_text(size = unit(6, "points")),
    axis.title = element_text(size = rel(0.6)),
    legend.position = "top",
    legend.margin=margin(0,0,-10,0),
    axis.text.y = element_text(size = unit(6, "points")),
    axis.text.x = element_text(angle = 0, hjust = 0.6,
                               size = unit(6, "points")),
    panel.grid.major.y = element_blank(),
    plot.tag.position = c(0.01, 0.98)
  ) +
  facet_grid2(. ~ condition, scales = "fixed")

D2 <- spikeins_join %>% 
  filter(condition == "Abundance") %>%
  mutate(condition = "Abundance\n") %>%
  ggplot() +
  geom_vline(xintercept = 0) +
  annotate(xmin = -Inf, xmax = Inf, ymin = 26.5, ymax = Inf,
    fill = "#DC5E65",
    geom = "rect",
    alpha = 0.2) +
  annotate(xmin = -Inf, xmax = Inf, ymin = 15.5, ymax = -Inf,
    fill = "#0072B2",
    geom = "rect",
    alpha = 0.2) +
  geom_pointrange(
    aes(
      x = effect,
      y = mut_id,
      xmin = effect - 2 * error,
      xmax = effect + 2 * error,
      color = significance
    ),
    linewidth = 0.25,
    size = 0.1,
    show.legend = FALSE
  ) +
  theme_pubr(base_size = 13) +
  labs(
    x = "Midpoint shift\n+/- 2 standard errors",
    y = "") +
  scale_color_manual("", values = c("black", "lightgrey")) +
  scale_x_continuous(limits = c(-1,1),
                     breaks = c(-1,0,1)) +
  custom_theme +
  theme(
    panel.grid.major.x = element_blank(),
    strip.text.x = element_text(size = unit(6, "points")),
    axis.title = element_text(size = rel(0.6)),
    axis.text.y = element_blank(),
    plot.margin = margin(0,0,0,10),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(angle = 0, hjust = 0.6,
                               size = unit(6, "points")),
    panel.grid.major.y = element_blank(),
    plot.tag.position = c(0.01, 0.98)
  ) +
  facet_grid2(. ~ condition)

D <- D1 + (D2 + plot_layout(tag_level = "new")) + plot_layout(widths = c(3,1))
```

### Panel E
```{r supp-fig-3-E, fig.width=8, fig.height=8}
clinvar_df <- tyk2_clinvar_joined %>% 
  mutate(class = fct_recode(class, "Conflicting\nClassifications\nOf Pathogenicity" = "Conflicting classifications of pathogenicity",
                                       "Uncertain\nSignificance"  = "Uncertain significance",
                                       "Benign/\nLikely Benign" = "Benign/Likely benign"),
         class = if_else(is.na(class), "Not in ClinVar", class),
         class = factor(class, levels = c("Pathogenic",
                                          "Conflicting\nClassifications\nOf Pathogenicity",
                                          "Uncertain\nSignificance",
                                          "Benign/\nLikely Benign",
                                          "Not in ClinVar"))) %>%
  filter(condition %in% c("IFNa 100 U/mL", "Abundance")) %>%
  group_by(pos, aa) %>%
  filter(n() == 2) %>%
  ungroup()

counts <- clinvar_df %>% 
  count(class) %>%
  rename("count" = "n")

E <- clinvar_df %>% 
  left_join(counts, by = "class") %>% 
  arrange(class) %>%
  mutate(classifier_value_count = fct_inorder(paste0(class, "\n(", format(count/2, big.mark = ",", trim = TRUE),")"))) %>%
  ggplot(aes(
    x = statistic,
    y = classifier_value_count,
    color = classifier_value_count,
    fill = classifier_value_count)) +
  geom_vline(xintercept = 0, color = "lightgrey") +
  geom_quasirandom_rast(orientation = "y",
    size = 0.5,
    width = 0.2,
    varwidth = TRUE,
    show.legend = FALSE) +
  scale_color_manual(values = cbPalette) +
  scale_fill_manual(values = cbPalette) +
  facet_grid2(. ~ condition,
    scales = "free_x",
    space = "free") +
  labs(
    x = "Z statistic",
    y = "Clinvar annotation",
  ) +
  custom_theme + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.6),
    axis.text.y = element_text(angle = 0, hjust = 0.5),
    axis.text= element_text(size = unit(6, "points")),
    strip.text.y = element_text(angle = 0, size = unit(8, "points")),
    axis.title = element_text(size = unit(10, "points")),
    plot.tag.position = c(0.01, 0.98)
  )
```

### Composite

```{r supp-fig-3, fig.width=8.5, fig.height=11}
layout <- c(
  area(1, 1, 1, 1),
  area(1, 2, 1, 2),
  area(1, 3, 1, 3),
  area(2, 1, 2, 2),
  area(2, 3, 2, 3)
)
A + free(B, type = "label") + free(C, side = "l") + free(D) + E +
  plot_layout(heights = c(1, 1),
              guides = "keep",
              design = layout) +
  plot_annotation(tag_levels = "A") &
  theme(
    legend.key = element_blank(),
    panel.grid.major.y = element_blank(),
    axis.title = element_text(size = unit(8, "points")),
    axis.text = element_text(size = unit(6, "points")),
    plot.tag = element_text(size = unit(14, "points")),
    legend.text = element_text(size = unit(8, "points")),
    strip.text.x = element_text(size = unit(6, "points")),
    plot.tag.position = c(0.01, 1.01)
  )

```
