---
title: "Octant-BMS TYK2 Manuscript Data Visuals"
author: "Nathan Abell and Conor Howard"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = c("png", "pdf")
)

library(scico)
library(scales)
library(ggrepel)
library(ggbeeswarm)
library(janitor)
library(broom)
library(broom.mixed)
library(patchwork)
library(stringr)
library(tidyverse)

custom_theme <- theme_bw(
  base_size = 15
) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
  )
theme_set(custom_theme)

scale_fill_scico_mid <- function(..., mid = 0, alpha = NULL, begin = 0, end = 1, direction = 1, reverse = TRUE, palette = "broc") {
  force(mid)
  ggplot2::continuous_scale(
    aesthetics = "fill",
    scale_name = "gradient2",
    palette = scales::gradient_n_pal(
      colours = scico::scico(256, alpha, begin, end, direction, palette),
      values = NULL, space = "Lab"
    ),
    guide = "colourbar",
    rescaler = function(x, to = c(0, 1), from = range(x, na.rm = TRUE)) {
      scales::rescale_mid(x, to, from, mid)
    },
    ...
  )
}
```

# Common Data Processing

```{r loading}
assay1 <- read_tsv("../sumstats/TYK2-run1.sumstats.tsv", show_col_types = FALSE) %>%
  mutate(assay = "assay1")

assay2 <- read_tsv("../sumstats/TYK2-run2.sumstats.tsv", show_col_types = FALSE) %>%
  mutate(assay = "assay2")

assay3 <- read_tsv("../sumstats/TYK2-run3.sumstats.tsv", show_col_types = FALSE) %>%
  mutate(assay = "assay3")

flow_data <- read_tsv("../sumstats/TYK2-vamp2.midpoints.tsv", show_col_types = FALSE) %>%
  mutate(aa = if_else(aa %in% c("X", "Stop", "*"), "Stop", aa))

assay_data <- bind_rows(assay1, assay2, assay3)  %>%
    group_by(assay) %>%
    mutate(fdr = p.adjust(p.value, method = "BH")) %>%
    ungroup()

treated <- assay_data %>% filter(condition != "None_0")
untreated <- assay_data %>%
  filter(condition == "None_0") %>%
  rename("log2FoldChange_Control" = "log2FoldChange",
         "log2StdError_Control" = "log2StdError") %>%
  select(-condition, -statistic, -p.value, -fdr)

sumstats <- inner_join(treated, untreated, by = c("chunk", "pos", "aa", "assay"))
contrast_sumstats <- sumstats %>%
  group_by(assay) %>%
  mutate(log2Contrast = log2FoldChange - log2FoldChange_Control,
         log2ContrastError = sqrt(log2StdError^2 + log2StdError_Control^2),
         statistic_contrast = log2Contrast/log2ContrastError,
         p.value_contrast = (1 - pnorm(abs(statistic_contrast))) * 2,
         fdr_contrast = p.adjust(p.value_contrast, method = "BH")) %>%
  ungroup()

write_tsv(contrast_sumstats, "../sumstats/TYK2.contrast.tsv")
```

# Figure 1

```{r child="fig-1.Rmd"}
```

# Figure 2

```{r child="fig-2.Rmd"}
```

# Figure 3

```{r child="fig-3.Rmd"}
```

# Supplementary Figure 2

```{r child="fig-2-supplement.Rmd"}
```
